# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MuseumsGIS
                                 A QGIS plugin
 MuseumsGIS GIS-plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-03
        copyright            : (C) 2022 by Peter Jensen Maring, Arkæologisk IT, Moesgaard Museum
        email                : pje@moesgaardmuseum.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MuseumsGIS class from file MuseumsGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .museumsgis import MuseumsGIS
    return MuseumsGIS(iface)
